<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download Forms</name>
   <tag></tag>
   <elementGuidId>aeeacca9-5e53-4ddc-a63e-9e3790a72efb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile-menu > ul > li:nth-of-type(4) > ul.submenu > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mobile-menu']/ul/li[4]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Download Forms&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aaad04cd-16a5-4f81-8a5b-be452f4d888b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bssrv.ac.in/downloadsPage</value>
      <webElementGuid>76bae233-1735-4b01-951b-e7a53eac69c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Forms</value>
      <webElementGuid>d32a0adc-b12d-45d6-9929-9307f316cdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-menu&quot;)/ul[1]/li[4]/ul[@class=&quot;submenu&quot;]/li[3]/a[1]</value>
      <webElementGuid>04d88b95-6bbd-4258-b9f0-c8a4bd00b29b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mobile-menu']/ul/li[4]/ul/li[3]/a</value>
      <webElementGuid>d08a0178-3fc2-494e-b335-51e3d581b5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Forms')]</value>
      <webElementGuid>89a490f5-179c-4740-894c-06c1b013a68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYLLABUS'])[1]/following::a[1]</value>
      <webElementGuid>22e15534-ceaa-447c-8b1f-505f1e3508e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGULATIONS AND GUIDELINES'])[1]/following::a[2]</value>
      <webElementGuid>7ad6b2d8-c5dc-4e0b-ba96-16431bd779aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department of Assamese'])[1]/preceding::a[3]</value>
      <webElementGuid>cb32d986-1b0f-4a50-ad38-1889bad536fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Forms']/parent::*</value>
      <webElementGuid>e9489506-55e1-4278-b398-22e48e3ca67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bssrv.ac.in/downloadsPage')]</value>
      <webElementGuid>c4c50567-1eda-48c3-803c-de705e824c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[3]/a</value>
      <webElementGuid>a55822e8-ae9b-4fc1-bf8b-97a409560e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bssrv.ac.in/downloadsPage' and (text() = 'Download Forms' or . = 'Download Forms')]</value>
      <webElementGuid>de85cd0d-4dcc-4da6-9cfe-0eb4d0de0e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
