<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GIRLS COMMON ROOM_meanmenu-reveal</name>
   <tag></tag>
   <elementGuidId>611f3ad1-c747-40de-bc24-d45df2541465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.meanmenu-reveal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='home']/div/div[2]/div/div/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.meanmenu-reveal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52003018-b1cf-4a1e-9090-bef91ba1a4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#nav</value>
      <webElementGuid>c628a4d3-8abb-4f83-ac74-b1bf72241c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>meanmenu-reveal</value>
      <webElementGuid>0f5b779a-fa28-4de7-a07b-0877fe97a571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;header-area&quot;]/div[@class=&quot;header-bottom-area header-sticky&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-left&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;mobile-menu mean-container&quot;]/div[@class=&quot;mean-bar&quot;]/a[@class=&quot;meanmenu-reveal&quot;]</value>
      <webElementGuid>2bc69cdd-8647-49e1-b4a6-f9f5136bbb5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='home']/div/div[2]/div/div/div[3]/div/div/a</value>
      <webElementGuid>0cea67eb-7572-4d64-a110-fbacbaa28ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GIRLS COMMON ROOM'])[1]/following::a[1]</value>
      <webElementGuid>6f2e79f0-83bd-4ca9-9a99-3a225bc58f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INCUBATION CENTRE'])[1]/following::a[2]</value>
      <webElementGuid>20b03cc2-4e53-4b82-9945-c133618a76c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[1]</value>
      <webElementGuid>0709754a-e98e-4134-bb77-048082c133d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About The University'])[2]/preceding::a[3]</value>
      <webElementGuid>9e4def4b-0502-42e8-8e3c-297b03504a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#nav')]</value>
      <webElementGuid>6a1bca96-1b1e-420e-b6dc-904da9b41f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>c15b8906-7f70-485b-bb0c-2efa388e52c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#nav']</value>
      <webElementGuid>58c4becc-d3d7-4d11-8f8d-14a1dfcda779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/a</value>
      <webElementGuid>8e8944b8-4bea-464d-9050-7fba1f17c57e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
