<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REGISTRAR</name>
   <tag></tag>
   <elementGuidId>0288acc5-def0-492f-a27c-4cdc46b133bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > ul.submenu > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mobile-menu']/ul/li[3]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;REGISTRAR&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4faf9a56-9e8e-406a-9faf-6bd45d8cdf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bssrv.ac.in/registrarPage</value>
      <webElementGuid>f58f92d5-506b-4740-b610-03c275e21860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REGISTRAR</value>
      <webElementGuid>a17542ce-2e2d-4f03-be2a-6d2c6945899b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-menu&quot;)/ul[1]/li[3]/ul[@class=&quot;submenu&quot;]/li[3]/a[1]</value>
      <webElementGuid>103ef9fa-0a18-4ef2-8060-3044b4d0ef36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mobile-menu']/ul/li[3]/ul/li[3]/a</value>
      <webElementGuid>fa462260-fe41-47e6-80ec-f850cd7356a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REGISTRAR')]</value>
      <webElementGuid>d5c6607a-8dda-4061-b382-e50aab4a3849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VICE CHANCELLOR'])[1]/following::a[1]</value>
      <webElementGuid>d63497e9-83f3-44d7-8f7d-d896dde3d786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHANCELLOR'])[1]/following::a[2]</value>
      <webElementGuid>fa835c27-4c9a-4d81-9555-ac4089fa56f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTROLLER OF EXAMINATIONS'])[1]/preceding::a[2]</value>
      <webElementGuid>99c4aa69-558c-4f70-9dbf-547484b7fa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPUTY REGISTRAR(ADMINISTRATION)'])[1]/preceding::a[3]</value>
      <webElementGuid>3770eaec-0501-49ab-82b7-566987967213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGISTRAR']/parent::*</value>
      <webElementGuid>98e17ba3-958b-42c1-9bee-7f38408a50e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bssrv.ac.in/registrarPage')]</value>
      <webElementGuid>30905e7e-c8bf-4701-8669-5a780b0a2d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/a</value>
      <webElementGuid>acfd958e-bacb-49c3-941d-3f2229fb8105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bssrv.ac.in/registrarPage' and (text() = 'REGISTRAR' or . = 'REGISTRAR')]</value>
      <webElementGuid>82939c37-55ce-4d0a-98de-13d9687d72b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
