<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SYLLABUS</name>
   <tag></tag>
   <elementGuidId>dd80054a-34c4-4ce2-9bb2-c6a812f1f46b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile-menu > ul > li:nth-of-type(4) > ul.submenu > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mobile-menu']/ul/li[4]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SYLLABUS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68168de1-43cb-4e91-b21d-bd82295d8366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bssrv.ac.in/pageunderconstructionPage</value>
      <webElementGuid>c5f54b10-2c73-4ea4-88f2-9bbd2e4d11e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SYLLABUS</value>
      <webElementGuid>58fb259d-9b9b-4fc8-aa5b-e008586afbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-menu&quot;)/ul[1]/li[4]/ul[@class=&quot;submenu&quot;]/li[2]/a[1]</value>
      <webElementGuid>b8ccd31d-1359-46a9-87bb-f8311eabadb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mobile-menu']/ul/li[4]/ul/li[2]/a</value>
      <webElementGuid>334be478-15cb-4f54-886b-e8049b22c3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SYLLABUS')]</value>
      <webElementGuid>6860f478-fc76-47c9-b5c8-2884137652e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGULATIONS AND GUIDELINES'])[1]/following::a[1]</value>
      <webElementGuid>5ca6d914-fc14-4d8f-8568-bc248e0fd221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMMITTEES'])[1]/following::a[3]</value>
      <webElementGuid>0a702cec-ff0c-4f66-b9e3-eec6459c8afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Forms'])[1]/preceding::a[1]</value>
      <webElementGuid>88e95df9-e0f5-45c7-b32e-7c20fbe10432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SYLLABUS']/parent::*</value>
      <webElementGuid>87929911-c5bf-45bb-b5d8-6bf51af098e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bssrv.ac.in/pageunderconstructionPage')]</value>
      <webElementGuid>f9cf6d79-b07c-4fac-a3af-00373e0c929e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>01743c05-6bb7-4147-832f-971130c36588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bssrv.ac.in/pageunderconstructionPage' and (text() = 'SYLLABUS' or . = 'SYLLABUS')]</value>
      <webElementGuid>98f6208b-3955-4b8b-95ee-72beb9205be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
