<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_PROSPECTUS</name>
   <tag></tag>
   <elementGuidId>24b2c6e2-66b2-4200-86c9-abb7ed5450a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wp-block-button__link.wp-element-button > strong > mark.has-inline-color.has-accent-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='(till 11.55 pm)'])[1]/following::mark[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PROSPECTUS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>a218f8f9-0e07-4f1a-82d9-f143e21d9828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-inline-color has-accent-color</value>
      <webElementGuid>d31fe13f-2680-4099-a8e5-d4649a4e2b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROSPECTUS</value>
      <webElementGuid>c9c77773-c5b8-4dca-b0d6-8d832a0efc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home blog wp-custom-logo wp-embed-responsive&quot;]/div[@class=&quot;wp-site-blocks&quot;]/div[@class=&quot;wp-block-columns is-layout-flex wp-container-core-columns-is-layout-7 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column is-layout-flow wp-block-column-is-layout-flow&quot;]/div[@class=&quot;wp-block-buttons is-content-justification-center is-layout-flex wp-container-core-buttons-is-layout-1 wp-block-buttons-is-layout-flex&quot;]/div[@class=&quot;wp-block-button is-style-outline&quot;]/a[@class=&quot;wp-block-button__link wp-element-button&quot;]/strong[1]/mark[@class=&quot;has-inline-color has-accent-color&quot;]</value>
      <webElementGuid>3d58211b-8fca-42da-b62e-0ff91e3b4db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(till 11.55 pm)'])[1]/following::mark[1]</value>
      <webElementGuid>c16c0703-f0b1-4896-a757-85c3dc0d5cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELIGIBILITY'])[1]/preceding::mark[1]</value>
      <webElementGuid>aa5582d2-3b44-41e7-aabc-d3c666ab80b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FEES STRUCTURE'])[1]/preceding::mark[2]</value>
      <webElementGuid>7cf33f7d-ce4d-419c-98a0-45aa017a3634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROSPECTUS']/parent::*</value>
      <webElementGuid>566cd001-d73c-4cf9-97ba-560b6cbd2eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/strong/mark</value>
      <webElementGuid>b3923687-e67e-4ee6-966b-3dd4c7ecfa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'PROSPECTUS' or . = 'PROSPECTUS')]</value>
      <webElementGuid>999e992b-e342-407e-ac00-f037d068bd6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
