<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>636ad0b4-833d-48db-b6bc-78c2f1f202e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.meanmenu-reveal > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='home']/div/div[2]/div/div/div[3]/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.meanmenu-reveal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c42da427-ee3d-4236-9586-3c740976e650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;header-area&quot;]/div[@class=&quot;header-bottom-area header-sticky&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-left&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;mobile-menu mean-container&quot;]/div[@class=&quot;mean-bar&quot;]/a[@class=&quot;meanmenu-reveal&quot;]/span[1]</value>
      <webElementGuid>d4797d75-f9b6-4229-bb9e-f6c76b9e7247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='home']/div/div[2]/div/div/div[3]/div/div/a/span</value>
      <webElementGuid>214acade-76b2-4a82-9759-4eb7c2801c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/span</value>
      <webElementGuid>bee97070-2648-44ba-bfc8-d58fe564eafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
